# Generated by Django 4.2.5 on 2023-11-17 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usrprof', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'پروفایل', 'verbose_name_plural': 'پروقایل ها'},
        ),
    ]
